home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('Search/',views.course_search,name='search'),
    path('ContactUs/',views.ContactUsView.as_view(),name='contactus'),
    path('ContactUs/newsmate/',views.NewsMatecontactusView.as_view(),name="contactuss"),
    path('ContactUs/rules/',views.RulesView.as_view(),name='rules'),
    path('ContactUs/privacy/',views.PrivacyView.as_view(),name='privacy'),
    path('blog/',views.BlogView.as_view(),name='blog'),
    path('blogpost/<int:pk>/',views.BlogPostView.as_view(),name='blogpost'),
]

home/models.py
from django.db import models
from accounts.models import User

class Blog(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    icon = models.ImageField(upload_to='blog/',blank=True,null=True)
    slogan = models.CharField(max_length=100,blank=True,null=True)
    first_intro = models.CharField(max_length=100,blank=True,null=True)
    introduction = models.TextField(max_length=300,blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('BlogTag', through='BlogTagRelation', related_name='blogs')
    
    def __str__(self):
        return self.user.name
    
class BlogTag(models.Model):
    tag = models.CharField(max_length=30)

    def __str__(self):
        return self.tag

class BlogTagRelation(models.Model):  # custom through table
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    tag = models.ForeignKey(BlogTag, on_delete=models.CASCADE)

    def __str__(self):
        return self.tag.tag
    
class BlogTitleInfo(models.Model):
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE)
    title = models.CharField(max_length=30,blank=True,null=True)
    info = models.TextField(max_length=500,blank=True,null=True)

    def __str__(self):
        return self.title
    
class ContactUs(models.Model):
    checked = models.BooleanField(default=False,blank=True,null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    email = models.EmailField()
    number = models.CharField(max_length=11,blank=True,null=True)
    req_title = models.CharField(max_length=60,blank=True,null=True)
    req_pm = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.name} - {self.req_title}"
    
class NewsMate(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    email = models.EmailField()

    def __str__(self):
        return self.email

home/forms.py
from django import forms
from .models import BlogTagRelation, BlogTag,NewsMate,ContactUs
import re

class BlogTagRelationForm(forms.ModelForm):
    tag_name = forms.CharField(max_length=30, label="Tag")

    class Meta:
        model = BlogTagRelation
        fields = []  # چون داریم همه چیز رو دستی مدیریت می‌کنیم

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # مقدار اولیه رشته تگ رو بذار
        if self.instance and self.instance.pk and self.instance.tag:
            self.fields['tag_name'].initial = self.instance.tag.tag

    def clean_tag_name(self):
        tag_name = self.cleaned_data['tag_name'].strip()
        tag_obj, created = BlogTag.objects.get_or_create(tag=tag_name)
        return tag_obj

    def save(self, commit=True):
        tag_obj = self.cleaned_data['tag_name']
        self.instance.tag = tag_obj
        return super().save(commit=commit)


class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=60)
    email = forms.EmailField(widget=forms.EmailInput)
    number = forms.CharField(max_length=11)
    req_title = forms.CharField(max_length=60)
    req_pm = forms.CharField(max_length=500,min_length=50)
    check = forms.BooleanField(required=True,widget=forms.CheckboxInput)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not re.search(r'\.(com|net|org|edu)$', email, re.IGNORECASE):
            raise forms.ValidationError("Email must end with .com, .net, .org, or .edu")
        return email
    
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) < 8:
            raise forms.ValidationError('اسم نباید از هشت کاراکتر کوچیکتر باشد')
        if name[0].isdigit():
            raise forms.ValidationError('اسم نمیتواند با عدد شروع شود')
        return name
    
    def clean_number(self):
        number = str(self.cleaned_data.get('number'))
        if number[1] != "9" or number[0] != "0":
            raise forms.ValidationError('شماره تلفن درست نیست')
        return number
    
class ContactUsHomeForm(forms.Form):
    name = forms.CharField(max_length=60)
    email = forms.EmailField(widget=forms.EmailInput)
    req_pm = forms.CharField(max_length=500,min_length=50)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not re.search(r'\.(com|net|org|edu)$', email, re.IGNORECASE):
            raise forms.ValidationError("Email must end with .com, .net, .org, or .edu")
        return email
    
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) < 8:
            raise forms.ValidationError('اسم نباید از هشت کاراکتر کوچیکتر باشد')
        if name[0].isdigit():
            raise forms.ValidationError('اسم نمیتواند با عدد شروع شود')
        return name
    
class IndexContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name','email','req_pm']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not re.search(r'\.(com|net|org|edu)$', email, re.IGNORECASE):
            raise forms.ValidationError("Email must end with .com, .net, .org, or .edu")
        return email
    
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) < 8:
            raise forms.ValidationError('اسم نباید از هشت کاراکتر کوچیکتر باشد')
        if name[0].isdigit():
            raise forms.ValidationError('اسم نمیتواند با عدد شروع شود')
        return name


class NewsMateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = NewsMate
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not re.search(r'\.(com|net|org|edu)$', email, re.IGNORECASE):
            raise forms.ValidationError("Email must end with .com, .net, .org, or .edu")
        return email

home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,DetailView
from django.conf import settings
from .models import Blog,ContactUs,NewsMate
from courses.models import Course,Comments
from django.contrib import messages
from .forms import ContactUsForm,ContactUsHomeForm,NewsMateForm,IndexContactUsForm
from accounts.models import TeacherUser

class HomePage(View):
    template_name = 'home/index.html'
    form_class = IndexContactUsForm
    def get(self,request):
        co = Course.objects.all()
        cou = 0
        for i in co:
            cou += i.students.all().count()
        teachers = TeacherUser.objects.all()
        allrate = Comments.objects.all().count()
        if allrate != 0:
            allrate += (allrate)*100/co.count()
        return render(request,self.template_name,{'form':self.form_class(),'MU':settings.MEDIA_URL,'co':co,'cou':cou,
                                                  'teach':teachers,'rate':allrate})
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if ContactUs.objects.filter(user=request.user).exists():
                messages.error(request,'شما یک تیکت باز دارید')
                return render(request, self.template_name, {'form': form, 'MU': settings.MEDIA_URL})
            else:
                    cont = ContactUs.objects.create(user=request.user,name=data['name'],email=data['email'],req_pm=data['req_pm'])
                    messages.success(request,'تیکت شما ثبت شد')
                    cont.save()
                    return redirect('home:home')
        if form.errors:
            for field_name, error_list in form.errors.items():
                for error in error_list:
                    messages.error(request, error)

            for error in form.non_field_errors():
                messages.error(request, error)
        return render(request,self.template_name,{'form':form,'MU':settings.MEDIA_URL})


def course_search(request):
    query = request.GET.get('q', '')
    if query:
        Co = Course.objects.filter(name__icontains=query)
    else:
        Co = Course.objects.all()
    return render(request, 'courses/packages.html', {'Co': Co})



class ContactUsView(LoginRequiredMixin,View):
    template_name = 'home/contact-to-us.html'
    form_class = ContactUsForm
    def get(self,request):
        return render(request,self.template_name,{'form':self.form_class(),'MU':settings.MEDIA_URL})
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if ContactUs.objects.filter(user=request.user).exists():
                messages.error(request,'شما یک تیکت باز دارید')
                return render(request, self.template_name, {'form': form, 'MU': settings.MEDIA_URL})
            else:
                if data['check']:
                    cont = ContactUs.objects.create(user=request.user,name=data['name'],email=data['email'],number=data['number'],
                                                    req_title=data['req_title'],req_pm=data['req_pm'])
                    messages.success(request,'تیکت شما ثبت شد')
                    cont.save()
                    return redirect('home:contactus')
                else:
                    messages.error(request,'با قوانین موافقت کنید')
                    return redirect('home:contactus')

        if form.errors:
            for field_name, error_list in form.errors.items():
                for error in error_list:
                    messages.error(request, error)

            for error in form.non_field_errors():
                messages.error(request, error)
        return render(request,self.template_name,{'form':form,'MU':settings.MEDIA_URL})


class BlogView(ListView):
    template_name = 'home/blog.html'
    context_object_name = 'blog'
    model = Blog
    form_class = NewsMateForm
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['MU'] = settings.MEDIA_URL
        return context
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if NewsMate.objects.filter(email=data['email']).exists():
                messages.error(request,'شما قبلا عضو شده اید')
                return redirect('home:blog')
            else:
                new = NewsMate.objects.create(user=request.user,email=data['email'])
                new.save()
                messages.success(request,'شما به خبرنامه عضو شدید')
                return redirect('home:blog')

        if form.errors:
            for field_name, error_list in form.errors.items():
                for error in error_list:
                    messages.error(request, error)

            for error in form.non_field_errors():
                messages.error(request, error)
        return render(request,self.template_name,{'form':form})


class BlogPostView(DetailView):
    template_name = 'home/blog-post.html'
    context_object_name = 'blog'
    model = Blog
    def get_object(self,queryset=None):
        return get_object_or_404(Blog,pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['MU'] = settings.MEDIA_URL
        return context

class RulesView(View):
    template_name = 'home/rulls.html'
    def get(self,request):
        return render(request,self.template_name,{'MU':settings.MEDIA_URL})

class PrivacyView(View):
    template_name = 'home/privacy.html'
    def get(self,request):
        return render(request,self.template_name,{'MU':settings.MEDIA_URL})


class NewsMatecontactusView(LoginRequiredMixin,View):
    template_name = "home/contact-to-us.html"
    form_class = NewsMateForm
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if NewsMate.objects.filter(email=data['email']).exists():
                messages.error(request,'شما قبلا عضو شده اید')
                return redirect('courses:allcourses')
            else:
                new = NewsMate.objects.create(user=request.user,email=data['email'])
                new.save()
                messages.success(request,'شما به خبرنامه عضو شدید')
                return redirect('home:contactus')
        if form.errors:
            for field_name, error_list in form.errors.items():
                for error in error_list:
                    messages.error(request, error)

            for error in form.non_field_errors():
                messages.error(request, error)
        return render(request,self.template_name,{'form':form})

home/templates/home/blog-post.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}{{ blog.first_intro }}{% endblock %}
{% block css %}
  <link href="https://cdn.fontcdn.ir/Font/Persian/Vazir/Vazir.css" rel="stylesheet">
   <link rel="stylesheet" href="{% static 'home/css/blog-post.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}" />
  <link rel="stylesheet" href="{% static 'home/css/reset.css' %}">
  <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v33.003/Vazir-font-face.css" rel="stylesheet" />
     <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-…"
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
{% endblock %}
{% block body %}
  <div class="container">
    <div class="post-header">
      <h1>{{ blog.first_intro }}</h1>
      <div class="post-meta">تاریخ : {{ blog.created }} | نویسنده : {{ blog.user.name }}</div>
    </div>
    <img class="post-image" src="{{ blog.icon.url }}" alt="تصویر مقاله" />

    <div class="post-content">
      {% if blog.introduction %}
        <p>{{ blog.introduction }}</p>
      {% endif %}

    {% with first_titleinfo=blog.blogtitleinfo_set.first %}
      {% if first_titleinfo %}
        <h2>{{ first_titleinfo.title }}</h2>
        <p>{{ first_titleinfo.info }}</p>
      {% endif %}
    {% endwith %}

      {% if blog.slogan %}
      <blockquote>{{ blog.slogan }}</blockquote>
      {% endif %}

    {% for ti in blog.blogtitleinfo_set.all %}
      <h2>{{ ti.title }}</h2>
      <p>{{ ti.info }}</p>
    {% endfor %}

    <div class="tags">
      {% for tag in blog.tags.all %}
        <span>#{{ tag.tag }}</span>
      {% endfor %}
    </div>

      <a href="{% url 'home:blog' %}" class="back-link">⬅ بازگشت به لیست مقالات</a>
    </div>
  </div>
{% endblock %}

home/templates/home/blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'home/css/blog.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}" />
  <link rel="stylesheet" href="{% static 'home/css/reset.css' %}">
  <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v33.003/Vazir-font-face.css" rel="stylesheet" />
     <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-…"
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
{% endblock %}
{% block body %}
    <!-- PAGE HERO -->
    <section class="page-header">
      <h1>وبلاگ</h1>
      <nav class="breadcrumb">
        <a class="page-header__index" href="{% url 'home:home' %}">خانه</a>
        <span>/</span>
        <a class="breadcrumb__contact" href="{% url 'home:blog' %}">بلاگ</a>
      </nav>
    </section>

    <!-- blog-->

<section class="blog">
  <div class="container">
    <div class="blog__header">
      <h2 class="blog__title">آخرین مقالات</h2>
      <p class="blog__subtitle">جدیدترین مطالب آموزشی و اخبار را بخوانید</p>
    </div>
   <div class="blog__list">
    {% for blg in blog %}
      <article class="blog__item">
        <div class="blog__image-wrapper">
          <img src="{{ blg.icon.url }}" alt="blog1" class="blog__image" />
        </div>
        <div class="blog__content">
          <span class="blog__date">{{ blg.created }}</span>

              <h3 class="blog__item-title">{{ blg.first_intro }}</h3>
              <p class="blog__text">{{ blg.introduction|truncatewords:30 }} ....</p>

          <a href="{% url 'home:blogpost' blg.pk %}" class="blog__link">بیشتر بخوانید</a>
        </div>
      </article>
    {% endfor %}

    </div>
    <!-- <form class="blog__form" action="/load-more-articles" method="POST">
      <input type="hidden" name="action" value="load_more_articles">
      <button type="submit" class="blog__button">مشاهده بیشتر مقالات</button>
    </form> -->
  </div>
</section>







    <!-- ====================== subscribe====================== -->
<section class="subscribe-section">
  <div class="subscribe-container">
    <div class="subscribe-text">
      <p class="subscribe-subtitle">آیا تحت تاثیر خدمات شگفت‌انگیز هستید؟</p>
      <h2 class="subscribe-title">مشترک خبرنامه ما شوید</h2>
    </div>
    <form class="subscribe-form" action="{% url 'home:blog' %}" method="post">
      {% csrf_token %}
      <input type="email" name="email" value="{{ user.email }}" placeholder="آدرس ایمیل شما" required>
      <button type="submit">مشترک شدن</button>
    </form>
  </div>
</section>
{% endblock %}

home/templates/home/contact-to-us.html
{% extends 'base.html' %}
{% load static %}
{% block title %}contact us{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}" />
  <link rel="stylesheet" href="{% static 'home/css/reset.css' %}">
  <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v33.003/Vazir-font-face.css" rel="stylesheet" />
     <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-…"
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'home/css/contact-to-us.css' %}" />
{% endblock %}
{% block body %}
    <!-- CONTACT INFO -->
    <section class="contact-info">
      <div class="info-box">
        <div class="icon"><i class="fas fa-map-marker-alt"></i></div>
        <div class="details">
          <strong>موقعیت ما</strong><br />
          ایران، استان تهران<br />
          میدان آزادی، خیابان ۹ شرقی
        </div>
      </div>

      <div class="info-box">
        <div class="icon"><i class="fas fa-envelope"></i></div>
        <div class="details">
          <strong>ایمیل ما</strong><br />
          hello@gmail.com<br />
          info@domain.com
        </div>
      </div>

      <div class="info-box">
        <div class="icon"><i class="fas fa-phone-alt"></i></div>
        <div class="details">
          <strong>تلفن</strong><br />
          ۰۲۱-۴۴۴۴۵۵۵۵<br />
          ۰۲۱-۵۵۵۵۸۷۶۴
        </div>
      </div>
    </section>

    <!-- contact -->
    <section class="contact">
      <div class="container">
        <div class="contact__header">
          <p class="contact__subtitle">ارسال پیام</p>
          <h2 class="contact__title">برای شروع آماده اید ؟</h2>
        </div>


        <form class="contact__form" action="{% url 'home:contactus' %}" method="POST">
          {% csrf_token %}
          <div class="contact__fields">
            <div class="contact__field">
              <label for="name" class="contact__label">نام</label>
              <input
                type="text"
                id="name"
                name="name"
                value="{{ request.user.name }}"
                class="contact__input"
                required
              />
            </div>
            <div class="contact__field">
              <label for="email" class="contact__label">ایمیل</label>
              <input
                type="email"
                id="email"
                name="email"
                value="{{ request.user.email }}"
                class="contact__input"
                required
              />
            </div>
            <div class="contact__field">
              <label for="phon-number" class="contact__label">شماره تلفن</label>
              <input
                type="text"
                id="phone"
                name="number"
                placeholder="09XXXXXXXXX"
                class="contact__input"
                required
              />
            </div>

            <div class="contact__field">
              <label for="title" class="contact__label">موضوع شما</label>
              <input
                type="title"
                id="title"
                name="req_title"
                class="contact__input"
                required
              />
            </div>

            <div class="contact__field contact__field--full">
              <label for="message" class="contact__label">پیام</label>
              <textarea
                id="message"
                name="req_pm"
                class="contact__textarea"
                rows="5"
                required
              ></textarea>
            </div>
          </div>
          <div class="rulls">
            <div class="rulls-container">
              <div class="rulls-text">
                پذیرفتن <a href="{% url 'home:rules' %}" class="rulls-link">قوانین و ضوابط</a> و
                <a href="{% url 'home:privacy' %}" class="rulls-link">حریم خصوصی.</a>
              </div>
              <input
                type="checkbox"
                id="checkbox"
                name="check"
                class="rulls-check"
                required
              />
            </div>
          </div>
          <button type="submit" class="contact__button">ارسال پیام</button>
        </form>
      </div>
    </section>

    <!--  map -->
<section class="map-section">
  <h2>موقعیت ما روی نقشه</h2>
  <div class="map-container">
    <iframe
      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d648517.8196083241!2d50.57409142167722!3d35.69306778396116!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8efbdfb2727d4d%3A0x813f8f0a96a84c4!2sTehran%2C%20Tehran%20Province%2C%20Iran!5e0!3m2!1sen!2s!4v1657815299900!5m2!1sen!2s"
      allowfullscreen=""
      loading="lazy"
      referrerpolicy="no-referrer-when-downgrade"
    ></iframe>
  </div>
</section>


<!-- ====================== subscribe====================== -->
<section class="subscribe-section">
  <div class="subscribe-container">
    <div class="subscribe-text">
      <p class="subscribe-subtitle">آیا تحت تاثیر خدمات شگفت‌انگیز هستید؟</p>
      <h2 class="subscribe-title">مشترک خبرنامه ما شوید</h2>
    </div>
    <form class="subscribe-form" action="{% url 'home:contactuss' %}" method="post">
      {% csrf_token %}
      <input type="email" name="email" value="{{ user.email }}" placeholder="آدرس ایمیل شما" required>
      <button type="submit">مشترک شدن</button>
    </form>
  </div>
</section>
{% endblock %}