accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('register/code/', views.VerifyCodeView.as_view(), {'mode': 'register'}, name='registercode'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('profile/<int:pk>/',views.UserProfileView.as_view(),name='profile'),
    path('userchangeprofile/<int:pk>/',views.UserChangeProfileView.as_view(),name='userchangeprof'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('teacherprofile/<int:pk>/',views.TeacherProfileView.as_view(),name='teacherprofile'),
    path('changepassword/',views.UserChangePasswordView.as_view(),name='changepass'),
    path('TeacherChangeProfile/',views.TeacherChangeProfileView.as_view(),name='teacherchangeprofile'),
    path('TeacherUploadCourse/',views.TeacherCourseUploadView.as_view(),name='courseupload'),
    path('userchangeemail/',views.UserChangeEmailView.as_view(),name='changeemail'),
    path('userchangeemail/code/', views.VerifyCodeView.as_view(), {'mode': 'changeemail'}, name='changeemailcode'),
    path('teacherprofile/<int:pk>/questions/',views.TeacherQuestionsView.as_view(), name='teacher_questions'),
    path('UserCart/<int:pk>/',views.UserCartView.as_view(),name='cart'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('courses/',views.AllCoursesView.as_view(),name='allcourses'),
    path('coursedetail/<int:pk>/',views.CourseDetailView.as_view(),name='coursedetail'),
    path('RemoveCourse/<int:id>/',views.TeacherRemoveCourseView.as_view(),name='removecourse'),
    path('EditCourse/<int:id>/',views.TeacherEditCourseView.as_view(),name='editcourse'),
    path('EditCourse/uploadtitle/<int:id>/',views.TeacherUploadTitleView.as_view(),name='uploadtitle'),
    path('EditCourse/uploadvideo/<int:id>/',views.TeacherVideoUploadView.as_view(),name='uploadvideo'),
    path('usersigncourse/<int:pk>/',views.UserSignCourseView.as_view(),name='signcourse'),
    path('AddTocart/<int:pk>/',views.UserAddToCartView.as_view(),name='addtocartcourse'),
    path('WatchTheCourse/<int:id>/',views.UserWatchCourseView.as_view(),name='watchthecourse'),
    path('WatchTheCourse/<int:id>/<int:video_id>/',views.UserWatchCourseView.as_view(), name='watch_course_video'),
    path('userlikecourse/<int:id>/',views.UserLikeCourseView,name='uprate'),
    path('teacherrespondtocomment/<int:id>/',views.TeacherCommentedToo.as_view(),name='teacherrespond'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('Search/',views.course_search,name='search'),
    path('ContactUs/',views.ContactUsView.as_view(),name='contactus'),
    path('ContactUs/newsmate/',views.NewsMatecontactusView.as_view(),name="contactuss"),
    path('ContactUs/rules/',views.RulesView.as_view(),name='rules'),
    path('ContactUs/privacy/',views.PrivacyView.as_view(),name='privacy'),
    path('blog/',views.BlogView.as_view(),name='blog'),
    path('blogpost/<int:pk>/',views.BlogPostView.as_view(),name='blogpost'),
]

templates/footer.html
<!-- footer -->
<footer class="footer">
  <div class="container">
    <div class="footer__top">
      <div class="footer__column footer__brand">
        <h3 class="footer__logo">OFFSITE</h3>
        <p class="footer__text">
          پلتفرم آموزشی Ledu ارائه‌دهنده بهترین دوره‌های آنلاین با تمرکز بر کیفیت و تجربه کاربری است.
        </p>
      </div>

      <div class="footer__column">
        <h4 class="footer__title">لینک‌های مفید</h4>
        <ul class="footer__menu">
          <li><a href="{% url 'home:home' %}" class="footer__link">صفحه اصلی</a></li>
          <li><a href="{% url 'courses:allcourses' %}" class="footer__link">دوره‌ها</a></li>
          <li><a href="#" class="footer__link">درباره ما</a></li>
          <li><a href="{% url 'home:contactus' %}" class="footer__link">تماس با ما</a></li>
        </ul>
      </div>

      <div class="footer__column">
        <h4 class="footer__title">ما را دنبال کنید</h4>
        <ul class="footer__social">
          <li><a href="#" class="footer__social-link">اینستاگرام</a></li>
          <li><a href="#" class="footer__social-link">تلگرام</a></li>
          <li><a href="#" class="footer__social-link">توییتر</a></li>
        </ul>
      </div>
    </div>

    <div class="footer__bottom">
      <p class="footer__copyright">
        © تمامی این قالب توسط تیم WEBRAH در سال 1404 ساخته شده
      </p>
    </div>
  </div>
</footer>

templates/navbar.html
   
  <header class="header">
    <div class="header__container">
      <a class="header__logo" href="#">OFFSITE</a>
         <div class="hamburger" id="hamburger">
      <span></span>
      <span></span>
      <span></span>
    </div>


    <nav class="mobile-nav" id="mobileNav">
      <ul>
        <li><a href="{% url 'home:home' %}">خانه</a></li>
        <li><a href="{% url 'courses:allcourses' %}">دوره‌ها</a></li>
        <li><a href="{% url 'home:blog' %}">وبلاگ</a></li>
        <li><a href="{% url 'home:contactus' %}">تماس با ما</a></li>
      </ul>
    </nav>
      <nav class="header__nav" id="navMenu">
        <ul class="header__menu">
          <li class="header__item"><a href="{% url 'home:home' %}" class="header__link">خانه</a></li>
          <li class="header__item"><a href="{% url 'courses:allcourses' %}" class="header__link">دوره‌ها</a></li>
          <li class="header__item"><a href="{% url 'home:blog' %}" class="header__link">وبلاگ</a></li>
          <li class="header__item"><a href="{% url 'home:contactus' %}" class="header__link">تماس با ما</a></li>
        </ul>
      </nav>
     <form action="{% url 'home:search' %}" method="get" class="header__form">
  <div class="header__icons">
    <input type="search" class="header__search" name="q" placeholder="جستجوی دوره‌ها..." />
    <button class="header__burger" id="burgerBtn" type="button"><i class="fa fa-bars"></i></button>
    <button class="search-btn" type="submit">
  <i class="fa fa-search"></i>
</button>
    {% if user.is_authenticated and user.is_teacher %}
    <a href="{% url 'accounts:teacherprofile' user.teacher.pk %}">
    <img class="header__prof" src="{{user.teacher.icon.url}}" alt="">
    </a>
    {% elif user.is_authenticated and not user.is_teacher %}
    <a href="{% url 'accounts:cart' pk=request.user.cart.pk %}">
    <img class="header__prof" src="{{MU}}img/R.svg" alt="">
    </a>
    <a href="{% url 'accounts:profile' pk=request.user.profile.id %}">
    <img class="header__prof" src="{{user.profile.icon.url}}" alt="">
    </a>
    {% elif not user.is_authenticated %}
    <a href="{% url 'accounts:register' %}" class="header__register">ثبت نام</a>
    {% endif %}
  </div>
</form>

      
  </header>